---
APP_PATH: '/sprints'
USE_POSTGRES: true
USE_SSL: true
SPRINTS_NGINX_CONFIG_PATH: /etc/nginx/sites-available/sprints

CI_SSH_PUBLIC_KEY: 'your-CI-key'

API_HOSTNAME: "backend.server"

# Settings for Sprints. See sprints/config/settings/ for details.
ENV_TOKENS:
  # General
  # ------------------------------------------------------------------------------
  DJANGO_READ_DOT_ENV_FILE: false
  DJANGO_SETTINGS_MODULE: 'config.settings.production'
  DJANGO_SECRET_KEY: 'set-me-please'
  DJANGO_ADMIN_URL: 'admin/'
  DJANGO_ALLOWED_HOSTS: '.api.your.domain'

  FRONTEND_URL: 'https://your.domain'

  # Security
  # ------------------------------------------------------------------------------
  # TIP: better off using DNS, however, redirect is OK too
  DJANGO_SECURE_SSL_REDIRECT: false

  # Email
  # ------------------------------------------------------------------------------
  MAILGUN_API_KEY: ''
  DJANGO_SERVER_EMAIL: ''
  MAILGUN_DOMAIN: ''

  # AWS
  # ------------------------------------------------------------------------------
  DJANGO_AWS_ACCESS_KEY_ID: ''
  DJANGO_AWS_SECRET_ACCESS_KEY: ''
  DJANGO_AWS_STORAGE_BUCKET_NAME: ''

  # django-allauth
  # ------------------------------------------------------------------------------
  DJANGO_ACCOUNT_ALLOW_REGISTRATION: true

  # Gunicorn
  # ------------------------------------------------------------------------------
  WEB_CONCURRENCY: 4

  # Sentry
  # ------------------------------------------------------------------------------
  SENTRY_DSN: ''


  # Redis
  # ------------------------------------------------------------------------------
  REDIS_URL: 'redis://redis:6379/0'

  # Celery
  # ------------------------------------------------------------------------------
  CELERY_BROKER_URL: 'redis://redis:6379/0'

  # Flower
  CELERY_FLOWER_USER: 'set-me-please'
  CELERY_FLOWER_PASSWORD: 'set-me-please'

  # Jira
  JIRA_SERVER: 'https://jira.server'
  JIRA_USERNAME: 'username'
  JIRA_PASSWORD: 'password'
  JIRA_CELL_ROLE_ACCOUNT: 1
  JIRA_CELL_ROLES: '{}'

  # Google
  GOOGLE_API_PRIVATE_KEY: 'set-me-please'
  GOOGLE_API_CLIENT_EMAIL: 'set-me-please'
  GOOGLE_SPILLOVER_SPREADSHEET: 'set-me-please'
  GOOGLE_CONTACT_SPREADSHEET: 'set-me-please'
  GOOGLE_AVAILABILITY_RANGE: 'set-me-please'
  GOOGLE_ROTATIONS_SPREADSHEET: 'set-me-please'
  GOOGLE_ROTATIONS_RANGE: 'set-me-please'

  # PostgreSQL
  # ------------------------------------------------------------------------------
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: 5432
  POSTGRES_DB: 'sprints'
  POSTGRES_USER: 'postgres_user'
  POSTGRES_PASSWORD: 'postgres_password'

  # JWT
  # JWT_ACCESS_TOKEN_LIFETIME_HOURS: 3
  # JWT_REFRESH_TOKEN_LIFETIME_DAYS: 30

  # Parallel requests
  # WEB_CONCURRENCY: 4
  # MULTIPROCESSING_POOL_SIZE: 4
  # MULTIPROCESSING_TIMEOUT: 30

  DATABASE_URL: 'postgres://postgres_user:postgres_password@postgres/sprints'

all_env_tokens: "{{ ENV_TOKENS | combine( CUSTOM_ENV_TOKENS ) }}"
