---

- name: install nginx apt package
  apt:
    name: nginx

- name: disable nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: set up global nginx SSL settings
  copy:
    src: nginx-ssl
    dest: /etc/nginx/conf.d/ssl.conf
  notify:
    - reload nginx

# Release port 80, which is needed by e.g. the load-balancer role.
- name: reload nginx if required
  meta: flush_handlers
