- name: Install Python 2
  hosts: accounting:backup-prune:chat:elasticsearch:load-balancer:mongodb:rabbitmq:relay:postgres
  become: true
  gather_facts: false
  tasks:
    - raw: "[ -e /usr/bin/python ] || sudo apt-get update -qq && sudo apt-get install -qq python"

- name: Set up backup-prune server
  hosts: backup-prune
  become: true
  roles:
    - name: common-server
      COMMON_SERVER_NO_BACKUPS: true
    - forward-server-mail
    - name: 'pmbauer.tarsnap'

- name: Install backup pruner
  hosts: backup-prune
  become: true
  tasks:
    - include: backup-pruner.yml

- name: Set up MySQL servers
  hosts: mysql
  become: true
  roles:
    - common-server
    - mysql
    - geerlingguy.mysql
    - forward-server-mail
    - filebeat

- name: Set up PostgreSQL servers
  hosts: postgres
  become: true
  roles:
    - common-server
    - postgres
    - geerlingguy.postgresql
    - forward-server-mail
    - filebeat

- name: Set up MongoDB servers
  hosts: mongodb
  become: true
  roles:
    - common-server
    - mongodb
    - greendayonfire.mongodb
    - forward-server-mail
    - filebeat

- name: Set up Dalite servers
  hosts: dalite
  become: true
  roles:
    - name: common-server
      TARSNAP_KEY: "{{ DALITE_LOGROTATE_TARSNAP_KEY }}"
      TARSNAP_KEY_REMOTE_LOCATION: "/root/tarsnap-logrotate.key"
      TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/dalite-pre-backup.sh"
      TARSNAP_BACKUP_SCRIPT_LOCATION: "{{ DALITE_TARSNAP_BACKUP_SCRIPT }}"
      TARSNAP_ARCHIVE_NAME: "dalite-logs"
      TARSNAP_CACHE: "/var/cache/tarsnap-logrotate"
      TARSNAP_BACKUP_FOLDERS: "{{ DALITE_LOG_DOWNLOAD_LOG_DIR }} {{ DALITE_LOG_DOWNLOAD_DB_DIR }}"
      TARSNAP_BACKUP_SNITCH: "{{ DALITE_LOG_TARSNAP_SNITCH }}"
      # Backup of logs is initiated by logrotate, which incidentally
      # also creates data to be backed up.
      TARSNAP_CRONTAB_STATE: "absent"
    - forward-server-mail
    - dalite
    - backup-swift-container

- name: Set up load-balancing servers
  hosts: load-balancer
  become: true
  roles:
    - common-server
    - forward-server-mail
    - load-balancer
    - filebeat

- name: Set up rabbitmq servers
  hosts: rabbitmq
  become: true
  roles:
    - common-server
    - forward-server-mail
    - rabbitmq
    - filebeat

- name: Set up elasticsearch servers
  hosts: elasticsearch
  become: true
  roles:
    - common-server
    - forward-server-mail
    - elasticsearch

- name: Set up internal mail relay
  hosts: relay
  become: true
  roles:
    - common-server
    - postfix

- name: Set up Mattermost chat server
  hosts: chat
  become: true
  roles:
    - common-server
    - forward-server-mail
    - mattermost
    - crafty
    - link-shortener

- name: Set up OpenCraft Accounting Automation application
  hosts: accounting
  become: true
  roles:
    - common-server
    - forward-server-mail
    - geerlingguy.nginx
    - geerlingguy.certbot
    - accounting
