# Note: due to security concerns we prefer using git hashes than ansible versions.

- name: geerlingguy.security
  src: https://github.com/geerlingguy/ansible-role-security
  version: af8b13833290ccae2ce1d2c9cce78862ddd3666c

- name: geerlingguy.nginx
  src: https://github.com/geerlingguy/ansible-role-nginx
  version: e81825546577cfb300efbcaec32aae4716561385

# Any version after this requires Ansible >= 2.4.
- name: geerlingguy.certbot
  src: https://github.com/geerlingguy/ansible-role-certbot
  version: 574c0843c8620f299ff67acbf35c9a6aa45121d0

- name: kamaln7.swapfile
  src: https://github.com/kamaln7/ansible-swapfile
  version: 8eb0e18d90a7f25b6658fbf56bcba01b84a664fc

- name: pmbauer.tarsnap
  src: https://github.com/pmbauer/ansible-tarsnap
  version: 7a625912409a0be2a3bf48967c60c5328ae2f3b2

- name: backup-to-tarsnap
  src: https://github.com/open-craft/ansible-backup-to-tarsnap
  version: origin/master

- name: common-server
  src: https://github.com/open-craft/ansible-common-server
  version: origin/master

- name: configure-apt
  src: https://github.com/open-craft/ansible-configure-apt
  version: origin/master

- name: sanity-checker
  src: https://github.com/open-craft/ansible-sanity-checker/
  version: origin/master

- name: forward-server-mail
  src: https://github.com/open-craft/ansible-forward-server-mail
  version: origin/master

- name: backup-swift-container
  src: https://github.com/open-craft/ansible-backup-swift-container
  version: origin/master

- name: dalite
  src: https://github.com/open-craft/ansible-dalite
  version: origin/master

- name: load-balancer
  src: https://github.com/open-craft/ansible-load-balancer
  version: origin/master

- name: rabbitmq
  src: https://github.com/open-craft/ansible-rabbitmq
  version: origin/master

- name: elasticsearch
  src: https://github.com/open-craft/ansible-role-elasticsearch
  version: origin/master

- name: filebeat
  src: https://github.com/open-craft/ansible-role-filebeat
  version: uman/updates

- name: postfix
  src: https://github.com/open-craft/ansible-postfix
  version: origin/master

- name: mattermost
  src: https://github.com/open-craft/ansible-mattermost
  version: origin/master

- name: crafty
  src: https://github.com/open-craft/ansible-crafty
  version: origin/master

- name: link-shortener
  src: https://github.com/open-craft/ansible-link-shortener
  version: origin/master

- name: accounting
  src: https://github.com/open-craft/ansible-accounting
  version: origin/master

- name: geerlingguy.mysql
  src: https://github.com/geerlingguy/ansible-role-mysql
  version: c71ded56d87c8df606210b59f045ed4c3f1f98ff

- name: mysql
  src: https://github.com/open-craft/ansible-mysql
  version: origin/master

- name: postgres
  src: https://github.com/open-craft/ansible-postgres
  version: origin/master

# Can change to upstream repo when https://github.com/geerlingguy/ansible-role-postgresql/pull/33 merges
- name: geerlingguy.postgresql
  src: https://github.com/open-craft/ansible-role-postgresql
  version: f7e8cb6bb1633511953069fe72b9440bd2db500a

- name: mongodb
  src: https://github.com/open-craft/ansible-mongodb
  version: origin/master

- name: greendayonfire.mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb
  version: 1ba531c5c68a4cf684410c50e7286ffd7742b848
