---

# Certbot
CERTBOT_DOMAIN_NAME: "{{ LANDING_SITE_HOSTNAME }}"
CERTBOT_ADDITIONAL_DOMAINS:
  - "{{ DEFAULT_SITE_HOSTNAME }}"
  - "{{ MAINTENANCE_SITE_HOSTNAME }}"
COMMON_SERVER_INSTALL_CERTBOT: true
