# TARSNAP #####################################################################

TARSNAP_BACKUP_FOLDERS: "{{ redis_dir }} /etc/letsencrypt"
TARSNAP_BACKUP_PRE_SCRIPT: "{{ REDIS_SCRIPTS_DIR }}/{{ REDIS_BACKUP_COMMAND }}"

# FILEBEAT ####################################################################

filebeat_prospectors:
  - fields:
      type: "redis"
    paths:
      - "{{ REDIS_LOG_DIR }}/*.log"
