# TARSNAP #####################################################################

TARSNAP_BACKUP_FOLDERS: "{{ REDIS_BASE_DIR }} /etc/letsencrypt"
TARSNAP_BACKUP_PRE_SCRIPT: "{{ REDIS_SCRIPTS_DIR }}/{{ REDIS_BACKUP_COMMAND }}"

# FILEBEAT ####################################################################

filebeat_prospectors:
  - fields:
      type: "redis"
    paths:
      - "{{ REDIS_LOG_DIR }}/*.log"

# FLUENT-BIT ##################################################################

fluentbit_log_input:
  - Name: tail
    Path_Key: _path
    Inotify_Watcher: On
    Exclude_Path: "{{ fluentbit_logfile }}"
    DB: "{{ fluentbit_log_input_db_path }}"
    Path: "{{ REDIS_LOG_DIR }}/*.log"
