---
- name: "restart mailman3"
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "mailman3"
    - "mailman3-web"

- name: reload postfix
  service:
    name: postfix
    state: reloaded
