version: '3'

services:
  django: &django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:django-latest
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    restart: always
    command: /start

  redis:
    image: redis:5.0
    restart: always

  celeryworker:
    <<: *django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:celeryworker-latest
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:celerybeat-latest
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:flower-latest
    ports:
      - "127.0.0.1:5555:5555"
    command: /start-flower
