version: '3'

services:
  django: &django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:crafty-django
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
    command: /start

  redis:
    image: redis:5.0
    restart: always

  celeryworker:
    <<: *django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:crafty-celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:crafty-celerybeat
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: registry.gitlab.com/opencraft/dev/crafty-bot:crafty-flower
    ports:
      - "5555:5555"
    command: /start-flower
