---
- name: install mailman3 packages
  apt:
    name:
      - "mailman3-full"
  notify:
    - "restart mailman3"

- name: Allow 443 tcp port for mailman3 web
  ufw:
    rule: "allow"
    port: "443"
    proto: "tcp"

- name: Mailman3 web nginx proxy config
  template:
    src: "mailman3-nginx-proxy.conf.j2"
    dest: "/etc/nginx/sites-available/mailman3"
  notify:
    - "reload nginx"

- name: Mailman3 nginx proxy config sites-enabled
  file:
    src: "/etc/nginx/sites-available/mailman3"
    dest: "/etc/nginx/sites-enabled/mailman3"
    state: "link"
  notify:
    - "reload nginx"

- name: Mailman3 mailman.cfg
  template:
    src: "mailman.cfg.j2"
    dest: "/etc/mailman3/mailman.cfg"
  notify:
    - "restart mailman3"

- name: Mailman3 mailman-web.py
  template:
    src: "mailman-web.py.j2"
    dest: "/etc/mailman3/mailman-web.py"
  notify:
    - "restart mailman3"

- name: Mailman3 mailman-hyperkitty.cfg
  template:
    src: "mailman-hyperkitty.cfg.j2"
    dest: "/etc/mailman3/mailman-hyperkitty.cfg"
  notify:
    - "restart mailman3"
