---

# COMMON ######################################################################

COMMON_SERVER_NO_BACKUPS: true

# FILEBEAT ####################################################################

filebeat_prospectors:
  - fields:
      type: "backup-pruner"
    paths:
      - "{{ BACKUP_PRUNER_LOG_DIR }}/*.log"

# FLUENT-BIT  ##################################################################

fluentbit_log_input:
  - Name: tail
    Path_Key: _path
    Inotify_Watcher: On
    Exclude_Path: "{{ fluentbit_logfile }}"
    DB: "{{ fluentbit_log_input_db_path }}"
    Path: "{{ BACKUP_PRUNER_LOG_DIR }}/*.log"
