---

- name: restart networking
  service:
    name: systemd-networkd
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: Restart sshd
  service:
    name: "ssh"
    state: restarted
