---

# ELASTICSEARCH ###############################################################

elasticsearch_repo: "deb [trusted=yes] http://packages.elastic.co/elasticsearch/1.5/debian stable main"
elasticsearch_package: "elasticsearch=1.5.2"
elasticsearch_network_host: 0.0.0.0
elasticsearch_http_port: 9200
elasticsearch_script_inline: false
elasticsearch_script_indexed: false

# CONSUL ######################################################################

consul_service_config:
  service:
    name: "elasticsearch"
    tags: ["elasticsearch"]
    port: 9200
    enable_tag_override: true
    checks:
      - name: "Connect to Elasticsearch"
        tcp: "{{ inventory_hostname }}:9200"
        interval: "10m"

# FLUENT-BIT ##################################################################

fluentbit_log_input:
  - Name: tail
    Path_Key: _path
    Inotify_Watcher: On
    Exclude_Path: "{{ fluentbit_logfile }}"
    DB: "{{ fluentbit_log_input_db_path }}"
    Path: "{{ elasticsearch_log_dir }}/*.log"
