---
dependencies:
  - name: nginx-proxy
    NGINX_PROXY_CONFIG_PATH: "{{ SPRINTS_NGINX_CONFIG_PATH }}"
    NGINX_PROXY_PUBLIC_PORT: 443
    NGINX_PROXY_INTERNAL_PORT: 5000
    NGINX_PROXY_USE_SSL: "{{ USE_SSL }}"
    NGINX_PROXY_SERVER_NAME: "{{ API_HOSTNAME }}"
