---
# Playbooks for setting up the Certificate Manager.

- name: Set up certificate management servers.
  hosts: cert-manager
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: vault-ssh
      tags: 'vault-ssh'

    - role: cert-manager
      tags: 'cert-manager'
