---
- name: Set up the Crafty Bot application
  hosts: crafty-bot
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: docker-compose
      tags: 'docker'

    - role: crafty-bot
      tags: 'crafty-bot'
