---
- name: Set up the mail server instance with mail and mailing-list
  hosts: mail
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: vault-ssh
      tags: 'vault-ssh'

    - role: 'mail'
      tags: 'mail'
