---
# Playbook for setting up a PostgreSQL server.

- name: Set up PostgreSQL servers
  hosts: postgres
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: vault-ssh
      tags: 'vault-ssh'

    - role: postgres
      tags: 'postgres'

    - role: geerlingguy.postgresql
      tags: 'geerlingguy.postgresql'
