---
# Playbook for setting up the PR watcher notifier application

- name: Set up pr-watcher-notifier app
  hosts: pr-watcher-notifier
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: pr-watcher-notifier
