---
- name: Deploy a WordPress instance using docker
  hosts: wordpress-docker
  become: true
  roles:
    - role: docker-compose
      tags: 'docker'
    - role: wordpress-docker
      tags: 'wordpress-docker'
    - role: consul
      when: consul_servers | length > 0
    - role: node-exporter
      when: NODE_EXPORTER_PASSWORD is not none
    - role: fluent-bit
      tags: 'fluent-bit'
      when: fluentbit_host | length > 0
