---
- name: open HTTPS port on the firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 443

- name: mount /var/www
  mount: name=/var/www src=/dev/vdb1 fstype=ext4 state=mounted

- name: chown www-data /var/www
  file: path=/var/www mode=750 owner=www-data group=www-data state=directory

- name: mkdir /var/www/log
  file: path=/var/www/log mode=750 state=directory

- name: Ensure directory for config files exists
  file:
    path: /etc/nginx/sites-available/wordpress
    state: directory

- name: Copy nginx global configuration
  synchronize: src="global/" dest=/etc/nginx/global checksum=yes delete=yes owner=no group=no

- name: Add landing site nginx configuration
  template:
    src: ../templates/wordpress-nginx.j2
    dest: /etc/nginx/sites-available/wordpress/{{ LANDING_SITE_HOSTNAME }}.conf

- name: Add default site nginx configuration
  template:
    src: ../templates/default-nginx.j2
    dest: /etc/nginx/sites-available/wordpress/{{ DEFAULT_SITE_HOSTNAME }}.conf

- name: Add maintenance site nginx configuration
  template:
    src: ../templates/maintenance-nginx.j2
    dest: /etc/nginx/sites-available/wordpress/{{ MAINTENANCE_SITE_HOSTNAME }}.conf

- name: Find needed nginx configurations
  find:
    paths: /etc/nginx/sites-available/wordpress
  register: found

- name: Enable nginx site configurations
  file:
    src: "{{ item.path }}"
    dest: /etc/nginx/sites-enabled/{{ item.path | basename }}
    state: link
  with_items: "{{ found.files }}"
  notify:
    - reload nginx

