---

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - unzip
    - mysql-client

- name: Create server directories
  file:
    path: "/var/www/{{ item }}"
    state: directory
    mode: 755
  with_items:
    - "{{ LANDING_SITE_HOSTNAME }}"
    - "{{ DEFAULT_SITE_HOSTNAME }}"
    - "{{ MAINTENANCE_SITE_HOSTNAME }}"

- name: Download and extract latest version of wordpress
  unarchive:
    src: https://wordpress.org/latest.zip
    dest: "/var/www/{{ LANDING_SITE_HOSTNAME }}"
    owner: www-data
    group: www-data
    remote_src: yes

- name: Move files to correct directory
  shell: cp -r /var/www/{{ LANDING_SITE_HOSTNAME }}/wordpress/. /var/www/{{ LANDING_SITE_HOSTNAME }}

- name: Create configuration file
  template:
    src: ../templates/wp-config.php.j2
    dest: "/var/www/{{ LANDING_SITE_HOSTNAME }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Download and install plugins from list
  unarchive:
    src: "{{ item }}"
    dest: "/var/www/{{ LANDING_SITE_HOSTNAME }}/wp-content/plugins"
    owner: www-data
    group: www-data
    remote_src: yes
  with_items: "{{ WORDPRESS_INSTALL_PLUGINS }}"

- name: Clone compiled theme
  git:
    repo: "{{ WORDPRESS_THEME_REPO }}"
    version: "{{ WORDPRESS_THEME_VERSION }}"
    dest: "/var/www/{{ LANDING_SITE_HOSTNAME }}/wp-content/themes/opencraftv2"
    update: no

- name: Create database
  mysql_db:
    name: "{{ WORDPRESS_DATABASE_NAME }}"
    login_user: "{{ WORDPRESS_DATABASE_USER }}"
    login_password: "{{ WORDPRESS_DATABASE_PASSWORD }}"
    login_host: "{{ WORDPRESS_DATABASE_HOST }}"
    state: present
  when: "{{ WORDPRESS_DATABASE_RESTORE_FROM_BACKUP }}"

- name: Restore database backup
  mysql_db:
    name: "{{ WORDPRESS_DATABASE_NAME }}"
    login_user: "{{ WORDPRESS_DATABASE_USER }}"
    login_password: "{{ WORDPRESS_DATABASE_PASSWORD }}"
    login_host: "{{ WORDPRESS_DATABASE_HOST }}"
    state: import
    target: "{{ WORDPRESS_DATABASE_RESTORE_BACKUP_PATH }}"
  when: "{{ WORDPRESS_DATABASE_RESTORE_FROM_BACKUP }}"
