---
dependencies:
  - name: ernestas-poskus.prometheus
    prometheus_node_exporter_install: false
    prometheus_alert_manager_config_global:
     smtp_smarthost: '{{ PROMETHEUS_ALERT_MANAGER_SMTP_SMARTHOST }}'
     smtp_from: '{{ PROMETHEUS_ALERT_MANAGER_SMTP_FROM }}'
     smtp_auth_username: '{{ PROMETHEUS_ALERT_MANAGER_SMTP_USERNAME }}'
     smtp_auth_password: '{{ PROMETHEUS_ALERT_MANAGER_SMTP_PASSWORD }}'
  - name: nginx-proxy
    NGINX_PROXY_CONFIG_PATH: /etc/nginx/sites-available/prometheus
    NGINX_PROXY_PUBLIC_PORT: 443
    NGINX_PROXY_INTERNAL_PORT: 9090
    NGINX_PROXY_USERNAME: "{{ PROMETHEUS_BASIC_AUTH_USERNAME }}"
    NGINX_PROXY_PASSWORD: "{{ PROMETHEUS_BASIC_AUTH_PASSWORD }}"
  - name: nginx-proxy
    NGINX_PROXY_CONFIG_PATH: /etc/nginx/sites-available/alertmanager
    NGINX_PROXY_PUBLIC_PORT: 9043
    NGINX_PROXY_INTERNAL_PORT: 9093
    NGINX_PROXY_USERNAME: "{{ PROMETHEUS_BASIC_AUTH_USERNAME }}"
    NGINX_PROXY_PASSWORD: "{{ PROMETHEUS_BASIC_AUTH_PASSWORD }}"
  - name: nginx-proxy
    NGINX_PROXY_CONFIG_PATH: /etc/nginx/sites-available/grafana
    NGINX_PROXY_PUBLIC_PORT: 3443
    NGINX_PROXY_INTERNAL_PORT: 3000
